name: shop3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  plugin_platform_interface: ^2.1.8
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  uuid_v4: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
